### ISSUE TITLE
Separate weight initialization from training.

### ISSUE THREAD

**Issue by tamis-laan** [nyanp/tiny-cnn#10]
In many situations one would like to train a network multiple times. Currently this is not possible as the layer weights are then randomized and previous learning is lost.

**Comment by edgarriba** [comment]
@tamis-laan @longdt 
In last tiny-cnn version there's a new method initialize weights. Could you check again? Feedback is welcomed.

**Comment by tamis-laan** [comment]
Sorry I abandoned this library in favor of another library. I no longer have the code in question.

**Comment by edgarriba** [comment]
@tamis-laan thx!

@nyanp Closing this
