### ISSUE TITLE
Handle non-sequential model

### ISSUE THREAD

**Issue by nyanp** [nyanp/tiny-cnn#108]
Many of state-of-the-art models such as  [deep residual net](http://arxiv.org/abs/1512.03385) have branch/merge layer paths. tiny-cnn can't construct such models now.

**Comment by edgarriba** [comment]
what about replicate the same idea as in Torch with ParallelTable?
https://github.com/torch/nn/blob/master/ParallelTable.lua

**Comment by nyanp** [comment]
@edgarriba
Thanks:) I'm now refactoring network structure to handle DAG. it looks like mxnet's StaticGraph (and basic structure is similar to ParallelTable).

**Comment by edgarriba** [comment]
@nyanp oh, that's awesome. What's the current status ? We're about to start the gsoc. @bhack @mtamburrano Should be this the starting point?

**Comment by bhack** [comment]
Yes also the new [Keras functional API](http://keras.io/getting-started/functional-api-guide/) is interesting.

**Comment by nyanp** [comment]
@edgarriba @bhack @mtamburrano
Hi, congraturations on your acceptance to gsoc! I wasn't assigned as mentor, but I'd happy to support you :) I'll push my local experimental branch in this weekend, it may be the starting point (it may be incomplete version, and your ideas are very welcome)

**Comment by nyanp** [comment]
I love Keras's functional API, it is very flexible and user-friendly. As implementing functional api in c++ is a bit hard task, starting from simpler graph data structure seems good (we need such class as backend even when we decide to implement functional api).

**Comment by pansk** [comment]
Do you think this refactoring can have some relation to #71 as well?

**Comment by bhack** [comment]
@pansk We can probably do something in the GSoC on opencl side if we could reuse libdnn https://github.com/naibaf7/caffe/commit/3794cbf5c9cc6956f9db66ef510b1f97eeb970b1

**Comment by pansk** [comment]
If you manage to keep it open, I'll try to blend in cuDNN as well.

Anyway, libdnn is really an unfortunate choice for naming a dnn library. It's probably the best one, but it's *slightly* overloaded (https://github.com/botonchou/libdnn, https://github.com/tochikuji/chainer-libDNN, are just the first two...). :)

**Comment by nyanp** [comment]
@pansk 
> If you manage to keep it open, I'll try to blend in cuDNN as well.

Great idea :) They are now starting [their OpenCV's GSoC project](https://summerofcode.withgoogle.com/projects/#5784229849858048). Non-final version of @edgarriba 's proposal is opened [here](https://groups.google.com/forum/#!topic/opencv-gsoc-2016/445H3tyYwyI) , and timeline of project is [here](https://github.com/Itseez/opencv/wiki/GSoC_2016). tiny-cnn may be used as backend of OpenCV's dnn module.

@bhack do you have some plans to use open-communication tools for this project? (forum, wiki, github issue etc)

**Comment by bhack** [comment]
@nyanp Actually we are trying to organize the work by email and hangout. But we will use also github (for issue-pr) and the wiki.
/cc @vpisarev @nerei

**Comment by bhack** [comment]
Another interesting thing to take in consideration could be a native [network morphism](http://arxiv.org/abs/1603.01670) support in the API.

**Comment by edgarriba** [comment]
@nyap awesome this computational graph feature 24af38681ff56f56753de41ebcc11f60cf084aa5. @bhack Do you think that will be possible with this: https://github.com/nyanp/tiny-cnn/blob/feat/generic-computational-graph/tiny_cnn/nodes.h#L174

**Comment by nyanp** [comment]
@edgarriba @bhack I've worked a bit more and add simple example in db0a179 . Backward computation in generic graph is still incomplete, but it might be a starting point of your project.

To avoid duplicate or conflicting working, I want to know (and want to share among tiny-cnn community, if we can) the gsoc's project scope and schedule. Could you tell me the wiki pages, or send me your plan?

**Comment by bhack** [comment]
@nyanp We have a meeting between mentors next week to check that there are no overlapping technical activities between DNN students. So @edgar could start to propose preferred activities (other than pure integration of tinycnn in opencv) in this days.

**Comment by edgarriba** [comment]
@nyanp just checking your last commit and got some errors when compiling. The whole idea is pretty cool and seems promising. @bhack By now I suggest to focus on check that everything is working.

**Comment by edgarriba** [comment]
@nyanp I've pull requested a Doxygen automatic documentation generator in order to make easy the understanding of the whole project https://github.com/nyanp/tiny-cnn/pull/138. Meanwhile, I will try to adapt the comments in Doxygen format.

**Comment by nyanp** [comment]
@edgarriba thank you, I've merged it :) I'll write docs in doxygen format.

**Comment by edgarriba** [comment]
@nyanp 
This issue should be closed since in last version we can handle non-sequential models.
https://github.com/nyanp/tiny-cnn/releases/tag/v0.1.0

**Comment by nyanp** [comment]
@edgarriba 
Absolutely.
