### ISSUE TITLE
Hessian matrix

### ISSUE THREAD

**Issue by chenjunlinghao** [nyanp/tiny-cnn#113]
hello,I don't understand the effect of Hessian matrix, can you introduce it roughly?Thanks

**Comment by nyanp** [comment]
@chenjunlinghao 
In tiny-cnn, Hessian(2nd derivative) matrix are used by levenberg-marquardt algorithm. Roughly, the effect of using Hessian is faster convergence. For example, page 18 of [this slide](http://math.oregonstate.edu/~gibsonn/optpart2.pdf) shows that Gauss-newton and Levenberg-Marquardt (both use hessian) converge faster than steepest gradient descent algorithm.
But nowadays most of modern deep learning models are trained by 1st order & adaptive algorithm, such as adagrad or adadelta.

**Comment by chenjunlinghao** [comment]
Thank you! Your code was very useful for better understanding how it works.

**Comment by edgarriba** [comment]
@nyanp Should we close this?
