### ISSUE TITLE
Problem with topology of convolution network

### ISSUE THREAD

**Issue by Denzelmon** [nyanp/tiny-cnn#115]
I need to generate network for face recognition.
I use this topology

net << convolutional_layer<tan_h>(240, 240, 5, 1, 16)
<< average_pooling_layer<tan_h>(236, 236, 16, 2)
<< convolutional_layer<tan_h>(118, 118, 3, 16, 40)
<< average_pooling_layer<tan_h>(116, 116, 40, 2)
<< convolutional_layer<tan_h>(58, 58, 3, 40, 60)
<< average_pooling_layer<tan_h>(56, 56, 60, 2)
<< convolutional_layer<tan_h>(28, 28, 5, 60, 100)
<< average_pooling_layer<tan_h>(24, 24, 100, 2)
<< convolutional_layer <tan_h> (12, 12, 3, 100, 150)
<< average_pooling_layer <tan_h> (10, 10, 150, 2)
<< convolutional_layer <tan_h> (5, 5, 5, 150, 400)
<< fully_connected_layer <tan_h> (400, 12);

But program doesn't work. What problem is?

**Comment by pansk** [comment]
Can you elaborate the part "program doesn't work"? :)
It's really hard to understand otherwise.
Does it hang?
Does it throws?
Is something appearing on the console?
Have you tried to break down the process in single "net << something(...)" operations, and execute them step-by-step in a debugger? (or interleave them with cout << "something" << endl; to see when a line is failing)

**Comment by Denzelmon** [comment]
When I try to define a variable "net" i get an error message "Microsoft Visual C++ Runtime Library Expression: vector subscript out of range"

**Comment by pansk** [comment]
Replace the line with

net << convolutional_layer(240, 240, 5, 1, 16);
net << average_pooling_layer(236, 236, 16, 2);
net << convolutional_layer(118, 118, 3, 16, 40);
net << average_pooling_layer(116, 116, 40, 2);
net << convolutional_layer(58, 58, 3, 40, 60);
net << average_pooling_layer(56, 56, 60, 2);
net << convolutional_layer(28, 28, 5, 60, 100);
net << average_pooling_layer(24, 24, 100, 2);
net << convolutional_layer (12, 12, 3, 100, 150);
net << average_pooling_layer (10, 10, 150, 2);
net << convolutional_layer (5, 5, 5, 150, 400);
net << fully_connected_layer (400, 12);

and then run them step by step, trying to see which line fails.
Just an hint: the last convolutional can be replaced with a fully connected layer of size 5x5x150=3750 (I don't know how well the convolutional layer behave when producing a 1x1 result)

**Comment by Denzelmon** [comment]
Program failed in first line: "net << convolutional_layer(240, 240, 5, 1, 16);"
Program throwed error message as described above. 
When i change "net << convolutional_layer(240, 240, 5, 1, 16)"  to  "net << convolutional_layer(32, 32, 5, 1, 16);", it don't throw message. 
Is it possible that "tiny-cnn" can't work with image's size like 240x240 (or > 100 x 100) and working with small size like 32x32

p.s. net << convolutional_layer (5, 5, 5, 150, 400); It should work well ! :)

**Comment by pansk** [comment]
This is interesting.
It's not failing in the actual creation, but in move constructor. I'll try to fix this later today.

**Comment by Denzelmon** [comment]
Thank you!
The last value when it not failed "net << convolutional_layer(108, 108, 5, 1, 16);"

**Comment by pansk** [comment]
Oops.
That layer is *really* eating up 2GB of RAM.
I didn't track down the problem precisely, but there're two possible workarounds:
1) switch to x64 (and remove the 2GB-per-process limit) :)
2) change the number of task in batch-gradient-descent, found in config.h

```
#ifdef CNN_USE_OMP
#define CNN_TASK_SIZE 100
#else
#define CNN_TASK_SIZE 8
#endif
```

Change that 100 to something more reasonable memory-wise, like 20-25. Note that this might result in training underperformance.

**Comment by Denzelmon** [comment]
The problem with "error message" can be solved as follows: 
change "typedef unsigned short layer_size_t" in util.h  to 
"typedef unsigned int layer_size_t;"

**Comment by pansk** [comment]
Nope, that's no longer a problem.
It has been fixed more than a month ago: it's now defined as cnn_size_t, that again is defined in config.h (by default) as std::size_t.

Please update your sources :)

**Comment by pansk** [comment]
The PR #116 will allow the line

net << convolutional_layer(240, 240, 5, 1, 16);

to complete correctly, but since it already allocates almost 2GB, your program will probably fail on the next line without any of the workarounds I described above.

**Comment by Denzelmon** [comment]
Thanks. It's solved the problem!
