### ISSUE TITLE
Creating caffe_converter.bin

### ISSUE THREAD

**Issue by arnabgithub** [nyanp/tiny-cnn#125]
Hi, How exactly do I need to compile and link together  caffe.pb.cc and caffe_converter.cpp  in order to generate caffe_converter.bin ? Could you kindly give a little more detail on it?

thanks

**Comment by arnabgithub** [comment]
OK, I think I figured it out now.

**Comment by kzos** [comment]
@arnabgithub , Were you successful in compiling the same
