### ISSUE TITLE
How to use OpenMP in Qt project?

### ISSUE THREAD

**Issue by skir** [nyanp/tiny-cnn#126]
Hi, I am already using OpenMP in my project on Qt, which is being built with `cmake` and `make` and not `cmake`. Is it possible to make parallel network training? Maybe should I somehow add `cmake` to my project?

**Comment by nyanp** [comment]
Hi,
If you already using OMP in your project, all you have to do is to define CNN_USE_OMP before including tiny-cnn.

```cpp
#define CNN_USE_OMP
#include "tiny_cnn.h"
```

**Comment by skir** [comment]
Thanks, 
I thought that it would be more sophisticated solution. But it works.
