### ISSUE TITLE
Update example code on front page

### ISSUE THREAD

**Issue by Plankton555** [nyanp/tiny-cnn#129]
The example code on the front page (https://github.com/nyanp/tiny-cnn#examples) is currently not compilable. The error I got was the following:

    main.cpp:43:77: error: too few arguments to function ‘void tiny_cnn::parse_mnist_images(const string&, std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > >*, tiny_cnn::float_t, tiny_cnn::float_t, int, int)’
         parse_mnist_images(dataFolder + "train-images.idx3-ubyte", &train_images);
                                                                             ^
    In file included from /home/plankton/git_libs/tiny-cnn/tiny_cnn/tiny_cnn.h:51:0,
                 from main.cpp:5:
    /home/plankton/git_libs/tiny-cnn/tiny_cnn/io/mnist_parser.h:140:13: note: declared here
     inline void parse_mnist_images(const std::string& image_file,

It seems like some of the arguments to `parse_mnist_images()` were missing. By changing `parse_mnist_images("train-images.idx3-ubyte", &train_images);` to `parse_mnist_images("train-images.idx3-ubyte", &train_images, -1.0, 1.0, 2, 2);` (as in /examples/main.cpp) I got it to compile.

**Comment by nyanp** [comment]
@Plankton555 
Thank you very much for your information, I've fixed it! :+1:
