### ISSUE TITLE
Training with n_threads > 8 asserts when OpenMP is disabled

### ISSUE THREAD

**Issue by reunanen** [nyanp/tiny-cnn#132]
This code works (even though it's not very meaningful):

    network<mse, adagrad> net;
    net << fully_connected_layer<tan_h>(1, 2);

    std::vector<vec_t> data;
    std::vector<label_t> labels;

    const size_t tnum = 1000;

    for (size_t i = 0; i < tnum; i++) {
        bool in = bernoulli(0.5);
        bool label = bernoulli(0.5);

        data.push_back({ in * 1.0 });
        labels.push_back(label ? 1 : 0);
    }

    const int n_threads = 8;
    net.train(data, labels, tnum, 1, nop, nop, true, n_threads);

With OpenMP disabled, if I increase `n_threads` to 9 (or higher), I get:

    Assertion failed: y.size() == t.size(), file C:\Local\tiny-cnn\tiny_cnn/lossfunctions/loss_function.h, line 71

Anyone able to reproduce this?

**Comment by reunanen** [comment]
I'm on quad-core with hyperthreading, which may have something to do with the limit being 8. (Pure guesswork though.)

Anyway, if it looks like you can't reproduce, try `n_threads = 100`.

**Comment by reunanen** [comment]
No, it's not my number of cores – it's the fact that when not using OpenMP, `CNN_TASK_SIZE` [is 8](https://github.com/nyanp/tiny-cnn/blob/d996c749c189ad4d17f4242e2a88c55acd203e1b/tiny_cnn/config.h#L62).

Anyway, created a [pull request for a suggested fix](https://github.com/nyanp/tiny-cnn/pull/135).

**Comment by pansk** [comment]
I'm a bit surprised, that check is checking that two vectors are the same size, I think there's an error, but it lies elsewhere. I'll try to have a look at your test later (please add your config variables here, so I can rebuild the same test - I'll increase the number of threads since I think I have 6 cores here (+HT))

**Comment by reunanen** [comment]
@pansk : I agree, the assert is a bit misleading. That said, I already spent some time trying to figure this out, so please have a look at my [pull request](https://github.com/nyanp/tiny-cnn/pull/135).

Anyway `n_threads` = 9 should be fine, as long as you don't have `CNN_USE_OMP` defined anywhere (so `CNN_TASK_SIZE` is 8).

**Comment by pansk** [comment]
After checking #135, I agree with you.
PR #135 will solve more than this problem, it will entirely overcome the limitation on the number of threads, allowing an arbitrary number of thread to be passed to train (limited only by available memory). A big plus of this PR is that by specifying a number of threads less than CNN_TASK_SIZE, it will actually save memory, allowing training on big networks to run on 32-bit machines without going out-of-memory.
