### ISSUE TITLE
Problems to compile in Android ndk

### ISSUE THREAD

**Issue by fh127** [nyanp/tiny-cnn#133]
Hi, all.

I am using the tiny_cnn repository to in Android project that it use Android NDK, when I compile the android project , I have the next errors:

      In function 'void tiny_cnn::detail::load_weights_fullyconnected(const caffe::LayerParameter&, t      tiny_cnn::layer_base*)':  error: 'to_string' is not a member of 'std'

**Comment by nyanp** [comment]
@fh127 
It seems that Android NDK lacks some of c++11 standard library functions, including `std::to_string`. the easiest solution is write it yourself, before including tiny_cnn (see below).

[http://stackoverflow.com/questions/22774009/android-ndk-stdto-string-support](http://stackoverflow.com/questions/22774009/android-ndk-stdto-string-support)

**Comment by nyanp** [comment]
Now we've replaced std::to_string function for our own implementation. This error may be fixed :)

**Comment by patrikhuber** [comment]
@fh127 You can also use the [CrystaX NDK](https://www.crystax.net/en/android/ndk/10) which has much better C++11/14 support. Also, you can try to compile with the original NDK but use libc++, that has `std::to_string`.
In my opinion both of these solutions are better than providing an own `to_string` implementation here.

**Comment by reifsnider** [comment]
In order to use C++11 in Android you just have to add the relevant CPP flags to your build.gradle's android.ndk section:


model {

    <...snip...>

    android.ndk {

        <...snip...>

        stl = "c++_static"

        <...snip...>

        cppFlags.add("-std=gnu++11")
        CFlags.add("-std=gnu99")

        <...snip...>

    }

    <...snip...>

}

**Comment by shengxingdong** [comment]
update ndk to ndk-r11 can compile without problem.

**Comment by edgarriba** [comment]
@nyanp @shengxingdong If problem solved, should we close this issue?

**Comment by nyanp** [comment]
OK this issue should be closed. @edgarriba Thank you for helping clean-up my issue list ;)
