### ISSUE TITLE
problem with convolutional layer padding

### ISSUE THREAD

**Issue by zeno40** [nyanp/tiny-cnn#134]
using the MNIST dataset

nn << convolutional_layer<elu>(32, 32, 3, 1, 6, padding::same)
       << average_pooling_layer<elu>(32, 32, 6, 2)
       << convolutional_layer<elu>(16, 16, 3, 6, 16, padding::same)
       << average_pooling_layer<elu>(16, 16, 16, 2)
       << convolutional_layer<elu>(8, 8, 3, 16, 120, padding::same)
       << fully_connected_layer<elu>(120, 10)
   << fully_connected_layer<softmax>(10, 10);
    std::cout << "load models..." << std::endl;

gives an error

**Comment by zeno40** [comment]
`nn << convolutional_layer<elu>(32, 32, 3, 1, 6, `padding::same)
`
`     << average_pooling_layer<elu>(32, 32, 6, 2) 
`
`    << convolutional_layer<elu>(16, 16, 3, 6, 16, `padding::same)
`
`       << average_pooling_layer<elu>(16, 16, 16, 2)
`
`       << convolutional_layer<elu>(8, 8, 3, 16, 120, `padding::same)
`
`       << fully_connected_layer<elu>(120, 10)
`
`	   << fully_connected_layer<softmax>(10, 10);
`
`    std::cout << "load models..." << std::endl;
`

gives an error. Is this network definition wrong?

**Comment by pansk** [comment]
Hi Filip,
I think the last convolutional has 8*8*120=7680 outputs, but you're connecting it to a fully connected layer of just 120 inputs.
Marco

**Comment by zeno40** [comment]
Thanks Marco,
It's working perfectly now!
