### ISSUE TITLE
reset_weights is true by default

### ISSUE THREAD

**Issue by jpdoyle** [nyanp/tiny-cnn#136]
I realize this may be intended behavior for the use case that the authors have in mind, but I just wasted ~30 CPU-days because I didn't realize this was the default. I was training on a dataset that couldn't fit on disk uncompressed, so I did what seemed reasonable -- extract a batch, read the NN from a file, run the batch, write the NN back to the file, repeat for the next batch. But since this option is true by default, it deleted anything from those rounds once a later round started. I have fixed the problem now, but I think this is an unreasonable default.

**Comment by DozerTheCat** [comment]
Also  be careful that the solvers are not cleared of their persistent optimization data, otherwise they will not train efficiently.  You may have also worked around the data size issue by swapping the data vectors in the callback after the epoch.

**Comment by Ginto8** [comment]
Luckily, I am only doing vanilla gradient descent for this -- I am
attempting to replicate the same type of training that was done for
AlphaGo, and they didn't do anything very stateful. But that's good to keep
in mind.

**Comment by nyanp** [comment]
@Ginto8 
Thank you for your feedback :) Actually it is an intended behavior (mainly for backward-compatibility), but now I think your opinion is reasonable. I'll change this behavior in next release.

**Comment by Ginto8** [comment]
@nyanp Awesome, thanks. Thanks for making this library btw, it's really nice to have easy-to-use, fairly fast CNNs without having to go through driver hell.
