### ISSUE TITLE
random number generation for weight initialization with the same seed

### ISSUE THREAD

**Issue by jairodelgado** [nyanp/tiny-cnn#139]
When you try to initialize network weights actually no matter which distribution is used, the seed for the std::mt19937 generator is hard coded to 1 in the util/util.h file. This will cause some issues with local minima avoidance, etc.

**Comment by nyanp** [comment]
@jairodelgado 
Thanks, I've added `tiny_cnn::set_random_seed` function into branch to customize seed. It will be merged into master branch sooner.

**Comment by jairodelgado** [comment]
@nyanp great! thanks for this great library
