### ISSUE TITLE
How to compile in Ubuntu 14.04?

### ISSUE THREAD

**Issue by erogol** [nyanp/tiny-cnn#14]
I installed tbb and boost by apt-get but at the configuration stage it does not alert anything about these libraries. It outputs same as I ./waf configure alone. Is this the ./waf configure output with correct settings of tbb and boost libs?

Setting top to                           : /home/bla/tiny-cnn-master 
Setting out to                           : /home/bla/tiny-cnn-master/build 
Checking for program g++,c++             : g++ 
Checking for program ar                  : /usr/bin/ar 
'configure' finished successfully (0.025s)

**Comment by nyanp** [comment]
It seems correct output.
Do you receive error messages when you execute ./waf build ?

**Comment by davidstutz** [comment]
You can also use CMake (`sudo apt-get install cmake`) as follows:

    cmake_minimum_required(VERSION 2.8)
    
    find_package(TBB REQUIRED)
    include_directories(include/ ${TBB_INCLUDE_DIRS})
    
    add_executable(cnn_cli src/main.cpp)
    target_link_libraries(cnn_cli ${TBB_LIBRARIES})

But you may need to locate TBB manually, or use a custom `FindTBB.cmake`, e.g.:

    find_path (TBB_INCLUDE_DIR tbb/)
    find_library (TBB_LIBRARIES NAMES tbb)
    
    mark_as_advanced (TBB_INCLUDE_DIR TBB_LIBRARIES)

For example, you can put `FindTBB.cmake` in `cmake/` and add 

    set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")

to your `CMakeLists.txt`. Worked for me on Ubuntu 14.04 with TBB installed through `apt-get`. Remember to uncomment

    #define CNN_USE_TBB

in `config.h`.

**Comment by DelightRun** [comment]
I haved modified `wscript` file to fit *nix system, it works fine on my OS X. So please have a look at my [modified tiny-cnn project](https://github.com/DelightRun/tiny-cnn).
BTW, I have posted a `pull request` to author.

**Comment by gary30404** [comment]
@DelightRun How can you successfully run tiny-can on your OS X? I have tried many times and also your modified project but it can't work on my OS X. The error message like this:
ld: library not found for -lboost_timer-mt
I'm sure that boost library is in /usr/local/lib.

**Comment by edgarriba** [comment]
@erogol  @davidstutz In last tiny-cnn version this is fixed. TBB should be found by cmake.
@gary30404 Currently, tiny-cnn is dependecny free. No need of Boost.

@nyanp Closing this
