### ISSUE TITLE
Error at running computational graph

### ISSUE THREAD

**Issue by edgarriba** [nyanp/tiny-cnn#140]
@nyanp I set up a simple shallow convolutional network using the new computational graph feature. 
Compilation is okay, however I got the follow error at running time:

test_graph: /software/tiny-cnn/tiny_cnn/layers/layer.h:484: void tiny_cnn::connect(std::shared_ptr<tiny_cnn::layer_base>, std::shared_ptr<tiny_cnn::layer_base>, tiny_cnn::cnn_size_t, tiny_cnn::cnn_size_t): Assertion `out_shape.size() == in_shape.size()' failed.
Aborted (core dumped)

**Code:**

    #include <iostream>
    #include "tiny_cnn/tiny_cnn.h"

    using namespace tiny_cnn;
    using namespace tiny_cnn::activation;
    using namespace tiny_cnn::layers;

    using namespace std;

    int main(int argc, char** argv) {

      // declare nodes
      auto in = std::make_shared<input_layer>(shape3d(8, 8, 1));
     
      auto cnn = std::make_shared<
          convolutional_layer<tan_h> >(8, 8, 3, 1, 4); // C1, 1@8x8-in, 4@6x6-out
     
      auto pool = std::make_shared<
          average_pooling_layer<tan_h> >(6, 6, 4, 2); // S1, 4@6x6-in, 4@6x6-out
     
      auto out = std::make_shared<linear_layer<relu> >(3 * 3 * 4);

      // connect
      in << cnn << pool << out;
      
      network<graph> net;
      construct_graph(net, { in }, { out });
      
      vec_t in_data(8 * 8, 0.0);
      uniform_rand(in_data.begin(), in_data.end(), -1, 1);
      net.weight_init(weight_init::constant(2.0));
      net.init_weight();

      auto res = net.predict(in_data);
      std::cout << res[0] << "," << res[1] << "," << res[2] << std::endl;

     }

**Comment by nyanp** [comment]
@edgarriba 
Thanks for your fb :) I've fixed the problem and change assertion to exception with more helpful message in 0d7e39f.

**Comment by edgarriba** [comment]
@nyanp awesome! Still playing with this example and I realized that the forward propagation does nothing since somewhere when the graph is constructed the connections are not properly done.

**Comment by edgarriba** [comment]
While debugging the code I found that when connections are created, you allocate a temporal data_node instead of connecting the two nodes at once. I don't see why do you do that and if then all data will be duplicated o not.

https://github.com/nyanp/tiny-cnn/blob/feat/generic-computational-graph/tiny_cnn/layers/layer.h#L444

**Comment by nyanp** [comment]
@edgarriba 
I realized that data_node is bad name: it is **edge** of graph.
- all layers(operations) are representated as `node`
- nodes are connected via in/out `edge`
- `edge` holds data and gradient of tensor

So We must create `data_node` (should be renamed to `data_edge` or `edge`) while connecting nodes. I have no idea that this is the best design but tensor flow has very similar model. BTW current implemetation should have some bugs around node connection, so I'd be grad if you'll share the example code!

> Nodes typically implement mathematical operations, but can also represent endpoints to feed in data, push out results, or read/write persistent variables. Edges describe the input/output relationships between nodes. These data edges carry dynamically-sized multidimensional data arrays, or tensors.
https://www.tensorflow.org

conv operation usually requires 2or3 tensors (input data, weight and optionally bias), and output 1 tensor(output data). additional 1 output in tiny-cnn is needed for activation (other dnn frameworks treat activation as individual layer, but tiny-cnn doesn't)

**Comment by edgarriba** [comment]
@nyanp thx for your explanation! now it's more clear. I've pull requested some changes https://github.com/nyanp/tiny-cnn/pull/142 concerning to your tips. Besides, in the graph scheduling there's still something weird with the edges dimensionality. I'll will come up to you once I get a proper fix.
