### ISSUE TITLE
tiny-cnn for android 

### ISSUE THREAD

**Issue by zhangqianhui** [nyanp/tiny-cnn#158]
I use ndk compile tiny-cnn and make a android project. Can i public it by github ?

**Comment by nyanp** [comment]
@zhangqianhui
It's very interesting, of course welcome! :)
May I add a link to your project in tiny-cnn's documents?

**Comment by zhangqianhui** [comment]
of course , https://github.com/zhangqianhui/CnnForAndroid

**Comment by edgarriba** [comment]
@zhangqianhui Excellent project !

@nyanp 
We could add to docs an extra section to links project where tiny-cnn is used

**Comment by nyanp** [comment]
@zhangqianhui /cc @edgarriba 
Thanks! updated: https://github.com/nyanp/tiny-cnn/tree/master/doc
