### ISSUE TITLE
how to save the model file after learning ?

### ISSUE THREAD

**Issue by goodtogood** [nyanp/tiny-cnn#17]
first, thanks for this great job !

I wanna know  whether it is possible to save the model after learning ?

thx!

**Comment by gaomy3832** [comment]
It seems operator << is overloaded to output the parameters to files, and >> is for loading a model.

See tiny-cnn/src/main.cpp at line 142 for an example.
```
    // save networks
    std::ofstream ofs("LeNet-weights");
    ofs << C1 << S2 << C3 << S4 << C5 << F6;
```

**Comment by goodtogood** [comment]
thank you very much ,  gaomy3832 

you're right !  I'm so stupid ignoring such important lines.   >_<

**Comment by zhangqianhui** [comment]
thanks
