### ISSUE TITLE
current directory error when include tiny_cnn 

### ISSUE THREAD

**Issue by szad670401** [nyanp/tiny-cnn#176]
I use the tiny_cnn to my project using Jetbrain Clion . 
```
/Users/yujinke/ClionProjects/Unit_Test_CNN/tiny_cnn/tiny_cnn.h:28:10: fatal error: 'tiny_cnn/config.h' file not found
#include "tiny_cnn/config.h"
```
I find the config.h file. the "tiny_cnn"  is not current directory.
Should I rename the src code as
#include "tiny_cnn/config.h" -> #include "./config.h" ?

**Comment by nyanp** [comment]
@szad670401 
Hi, thank you for using tiny-cnn :) You need to add tiny-cnn's root directory into your project's include directories (I'm sorry but I have no idea how to do in Clion).

**Comment by szad670401** [comment]
I've solved the problem. I  add 
> INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR} )
to the CMAKEFILE
Now. It works well.

**Comment by edgarriba** [comment]
@nyanp should we close this thread?

**Comment by nyanp** [comment]
@edgarriba 
Yes, I close it.

**Comment by szad670401** [comment]
yes
but tinycnn just allow to design linear structural model

**Comment by jorgealemangonzalez** [comment]
I'm facing the same issue in clion also. Could you please @szad670401 tell me how to fix it, i tried to put that line in my CmakeLists.txt but doesn't solve the problem

**Comment by ghost** [comment]
Hi,@szad670401  @jorgealemangonzalez 
 I added a file, train.cpp, in the root directory, and added dd_executable(abc train.cpp) in cmakelists.txt. After compiling, how to run this train.cpp in clion.
