### ISSUE TITLE
Is there any test c++ file for the cifar-10 dataset?

### ISSUE THREAD

**Issue by higrepyo** [nyanp/tiny-cnn#179]
Hi.

I'm new to convolutional neural networks, and I'm currently trying to visualize the kernels(features) for each convolution layer for images(not numbers). 

I've tried the mnist example, but it's difficult to see the kernel shape.

Has anyone made a test.cpp file for cifar-10??

**Comment by edgarriba** [comment]
Which version are you using? Follow new tutorials
https://github.com/nyanp/tiny-cnn/blob/master/doc/How-Tos.md#visualize-convolution-kernels

**Comment by higrepyo** [comment]
@edgarriba I've never noticed the docs, thanks :)
