### ISSUE TITLE
nn.test result problem

### ISSUE THREAD

**Issue by shengxingdong** [nyanp/tiny-cnn#185]
In sample1_convnet, when i try to use 
std::vector<vec_t> result = nn.test(test_images);
It seems that the result is not correct, it is not the same as nn.test(test_images, test_labels).

The value of "max_index(result[i])" is not same as "nn.fprop_max_index(test_images[i])" .

I compared the result using this code:
for (int i = 0; i < 10; i++){
		cout << test_labels[i] << " vs " << max_index(result[i]) << " vs " << nn.fprop_max_index(test_images[i]) << endl;
		for (int k = 0; k < result[i].size(); k++){
			cout << result[i][k] << ",";
		}
		cout << endl;
	}

**Comment by nyanp** [comment]
@shengxingdong 
Thanks, it is a bug in tiny-cnn. I'll fix it!
