### ISSUE TITLE
errors when compile train.cpp in mnsit example

### ISSUE THREAD

**Issue by hellbago** [nyanp/tiny-cnn#218]
I got some compiler errors when i try to build train.cpp of mnist example. I use VS2013. Here is the output:
in tiny-cnn-master\tiny_cnn/nodes.h(61): error C2899: impossible to use typename outside of a model statement
tiny-cnn-master\tiny_cnn/layers/dropout_layer.h(58): error C2610:'tiny_cnn::dropout_layer::dropout_layer(tiny_cnn::dropout_layer &&)': 
It is not a special member function that you can set as default

Some suggestion for solving this problem?

**Comment by beru** [comment]
What about using Visual Studio 2015?
It seems Microsoft made a lot of improvements.
https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by nyanp** [comment]
@hellbago 
I've fixed this error in af9c8db . Please retry in the newest version. Thx!
