### ISSUE TITLE
can not build in vs2013

### ISSUE THREAD

**Issue by sjm1992st** [nyanp/tiny-cnn#231]
1>  main.cpp
1>C:\Users\user\Desktop\tiny-cnn-0.1.0\tiny_cnn/nodes.h(61): error C2899: 不能在模板声明之外使用类型名称
1>C:\Users\user\Desktop\tiny-cnn-0.1.0\tiny_cnn/nodes.h(62): error C2899: 不能在模板声明之外使用类型名称
1>C:\Users\user\Desktop\tiny-cnn-0.1.0\tiny_cnn/layers/dropout_layer.h(58): error C2610: “tiny_cnn::dropout_layer::dropout_layer(tiny_cnn::dropout_layer &&)”: 不是可默认为的特殊成员函数
1>C:\Users\user\Desktop\tiny-cnn-0.1.0\tiny_cnn/layers/dropout_layer.h(61): error C2610: “tiny_cnn::dropout_layer &tiny_cnn::dropout_layer::operator =(tiny_cnn::dropout_layer &&)”: 不是可默认为的特殊成员函数
how can i build it in visual studio?

**Comment by nyanp** [comment]
@sjm1992st 
Hi,
I've fixed in af9c8db . Please fetch the newest version, thx :)

**Comment by weisunding** [comment]
Dose not work for me, cannot compile in Visual Studio 2013. 

1>------ Build started: Project: AITrader, Configuration: Debug Win32 ------
1>  main.cpp
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(112): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>          d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(426) : see reference to class template instantiation 'tiny_dnn::Tensor<U,kDimensions,kConst,Allocator>' being compiled
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(112): error C2143: syntax error : missing ',' before '<'
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(177): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(177): error C2143: syntax error : missing ';' before '<'
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(177): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(293): error C2327: 'tiny_dnn::Tensor<U,kDimensions,kConst,Allocator>::array' : is not a type name, static, or enumerator
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(293): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(293): error C2143: syntax error : missing ',' before '<'
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(302): error C2327: 'tiny_dnn::Tensor<U,kDimensions,kConst,Allocator>::array' : is not a type name, static, or enumerator
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(302): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(302): error C2143: syntax error : missing ',' before '<'
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(418): error C2327: 'tiny_dnn::Tensor<U,kDimensions,kConst,Allocator>::array' : is not a type name, static, or enumerator
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(418): error C2143: syntax error : missing ';' before '<'
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(418): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\tiny-dnn\tiny_dnn\core\framework\tensor.h(418): error C2238: unexpected token(s) preceding ';'
1>d:\tiny-dnn\examples\main.cpp(96): warning C4244: '*=' : conversion from 'double' to 'tiny_dnn::float_t', possible loss of data
1>d:\tiny-dnn\examples\main.cpp(154): warning C4305: '=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(168): warning C4305: '*=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(199): warning C4305: 'argument' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(224): warning C4305: '=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(256): warning C4305: '*=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(309): warning C4305: 'argument' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(322): warning C4305: '=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(340): warning C4305: '*=' : truncation from 'double' to 'tiny_dnn::float_t'
1>d:\tiny-dnn\examples\main.cpp(361): warning C4305: 'argument' : truncation from 'double' to 'tiny_dnn::float_t'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Randl** [comment]
Visual Studio 2013isn't supported anymore

**Comment by busracankaya** [comment]
Is visual studio community 2013 still supported?

**Comment by beru** [comment]
It isn't supported anymore.
