### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sjm1992st** [nyanp/tiny-cnn#234]
when i change the  ''int minibatch_size = 10;'' to ''int minibatch_size = 64;'' in main.cpp line of 102,something error happened.

**Comment by sjm1992st** [comment]
vs2013 prompts a breakpoint in loss_function.h line 117 (  assert(y.size() == t.size());), In debug mode,i see the t.size=32 and y.size=64

**Comment by nyanp** [comment]
@sjm1992st 
Thanks for your report! It is caused when ```train_images.size() % minibatch_size != 0```. I'll fix it soon :)
