### ISSUE TITLE
Provide a tutorial of how to convert from my images dataset to idx3-ubyte file ?

### ISSUE THREAD

**Issue by RafaRuiz** [nyanp/tiny-cnn#24]
Hello.

I've read the page of MNIST: http://yann.lecun.com/exdb/mnist/

I still don't know how to get working this: I'm trying to use my own database of images and labels, but the script asks me for:

    parse_mnist_labels("train-labels.idx1-ubyte", &train_labels);
    parse_mnist_images("train-images.idx3-ubyte", &train_images);
    parse_mnist_labels("t10k-labels.idx1-ubyte", &test_labels);
    parse_mnist_images("t10k-images.idx3-ubyte", &test_images);

and I don't know how to convert from my database to those kind of files.

Does anyone have a clue ?
Thank you very much.

**Comment by nyanp** [comment]
@RafaRuiz ,

I've added wiki page about data formatting. I'm glad if it helps you :)
[https://github.com/nyanp/tiny-cnn/wiki/Data-Format](https://github.com/nyanp/tiny-cnn/wiki/Data-Format)

**Comment by RafaRuiz** [comment]
Simply great!!!

Thank you very much!

**Comment by GangFang** [comment]
Hi @RafaRuiz 

Does the mnisten library work for you? I cannot convert my data to .idx3 format properly with mnisten...

On one hand, the training process is just ineffective with the converted .idx3 and .idx1 data; on the other hand, trying to open the image stored in .idx3 in MATLAB I just got some weird images with a few original images mixing into one..

**Comment by GangFang** [comment]
Hi @RafaRuiz @nyanp 

Does the mnisten library work for you? I cannot convert my data to .idx3 format properly with mnisten...

On one hand, the training process is just ineffective with the converted .idx3 and .idx1 data; on the other hand, trying to open the image stored in .idx3 in MATLAB I just got some weird images with a few original images mixing into one..

**Comment by edgarriba** [comment]
@nyanp Should we close this?

**Comment by ragaDani** [comment]
Hi,
I am trying to use the mnisten library to convert my images to idx format. But I get 
"undefined reference boost::filesystem" error despite having libboost v1.58 installed in my Ubuntu 16.04 PC.

**Comment by nhule11** [comment]
Can anyone tell me how to load .idx3-ubyte in jupyter?
