### ISSUE TITLE
Using tiny-cnn on Xcode with C++ and OpenCV

### ISSUE THREAD

**Issue by Sthipp29** [nyanp/tiny-cnn#252]
I'm fairly new to neural networks and am trying to implement a basic CNN for the MNIST database. I've worked with C++ and OpenCV before, and have it setup to work on my Macbook. I have included the tiny_cnn directory in my project directory and in the Header Search Path, but for some reason, the build fails. It says that there is a Lexical or Preprocessor issue, and config.h is not found. Please advice as soon as possible!

**Comment by Sthipp29** [comment]
Sorry - fixed it :) I was using the wrong path for the header files.

**Comment by mirerfangheybi** [comment]
Hi dear @Sthipp29 could you please explain how you fixed this problem?
I've got tons of errors and warnings related to paths.
