### ISSUE TITLE
外部configファイルでネットワーク構造を指定したい

### ISSUE THREAD

**Issue by nyanp** [nyanp/tiny-cnn#3]

**Comment by edgarriba** [comment]
@nyanp Closing this

**Comment by nyanp** [comment]
This issue (tiny-cnn doesn't provide any format to serialize/deserialize a model) isn't solved yet, but this issue should be re-opened in English.

**Comment by bhack** [comment]
@nyanp I think that https://github.com/nyanp/tiny-cnn/issues/188 is enough for the discussion.

**Comment by nyanp** [comment]
@bhack 
I agree.
