### ISSUE TITLE
How CIFAR 10 dataset can be used in tiny-cnn like the MNIST dataset?

### ISSUE THREAD

**Issue by Shakib7** [nyanp/tiny-cnn#31]
I have the binary version of the dataset.
The binary version contains the files data_batch_1.bin, data_batch_2.bin, ..., data_batch_5.bin, as well as test_batch.bin. Each of these files is formatted as follows:
<1 x label><3072 x pixel>
...
<1 x label><3072 x pixel>
In other words, the first byte is the label of the first image, which is a number in the range 0-9. The next 3072 bytes are the values of the pixels of the image. The first 1024 bytes are the red channel values, the next 1024 the green, and the final 1024 the blue. The values are stored in row-major order, so the first 32 bytes are the red channel values of the first row of the image. 

Each file contains 10000 such 3073-byte "rows" of images, although there is nothing delimiting the rows. Therefore each file should be exactly 30730000 bytes long. 

There is another file, called batches.meta.txt. This is an ASCII file that maps numeric labels in the range 0-9 to meaningful class names. It is merely a list of the 10 class names, one per row. The class name on row i corresponds to numeric label i.

**Comment by nyanp** [comment]
@Shakib7 
Now I've added [ciar10_parser.h](https://github.com/nyanp/tiny-cnn/blob/master/tiny_cnn/cifar10_parser.h) for this purpose.

You can use it like this
```cpp
    // load CIFAR-10 dataset
    // http://www.cs.toronto.edu/~kriz/cifar.html
    std::vector<label_t> train_labels, test_labels;
    std::vector<vec_t> train_images, test_images;

    parse_cifar10("data_batch_1.bin", train_images, train_labels);
    parse_cifar10("data_batch_2.bin", train_images, train_labels);
    parse_cifar10("data_batch_3.bin", train_images, train_labels);
    parse_cifar10("data_batch_4.bin", train_images, train_labels);
    parse_cifar10("data_batch_5.bin", train_images, train_labels);
    parse_cifar10("test_batch.bin", test_images, test_labels);
```

**Comment by jethrotan** [comment]
an abortion cuccured with loading cifar10 datasets , the  break point at calc_hessian()

**Comment by nyanp** [comment]
@jethrotan 
Could you tell me your code of network construction and data loading?

**Comment by jethrotan** [comment]
using default nn:
 nn << convolutional_layer<tan_h>(32, 32, 5, 1, 6) // 32x32 in, 5x5 kernel, 1-6 fmaps conv
       << average_pooling_layer<tan_h>(28, 28, 6, 2) // 28x28 in, 6 fmaps, 2x2 subsampling
       << convolutional_layer<tan_h>(14, 14, 5, 6, 16,
                                     connection_table(connection, 6, 16)) // with connection-table
       << average_pooling_layer<tan_h>(10, 10, 16, 2)
       << convolutional_layer<tan_h>(5, 5, 5, 16, 120)
       << fully_connected_layer<tan_h>(120, 10);

data loading code:
parse_cifar10("data_batch_1.bin", &train_images, &train_labels, -1.0, 1.0, 0, 0);

**Comment by nyanp** [comment]
@jethrotan 

CIFAR-10 and MNIST has different input size.

CIFAR-10: 32x32 RGB images (so input size is 32x32x3=3072)
MNIST: 32x32 grayscale images (32x32x1=1024)

Input size of neural network must be corresponded with dataset size, so you should modify first layer like this:

nn << convolutional_layer(32, 32, 5, 3, 6) // 32x32 in, 5x5 kernel, 3-6 fmaps conv

**Comment by jethrotan** [comment]
yes,it works.thanks!

**Comment by edgarriba** [comment]
@nyanp Can we close this?
