### ISSUE TITLE
./waf build failed

### ISSUE THREAD

**Issue by ChenSiqin** [nyanp/tiny-cnn#32]
I installed tiny-cnn using the command:./waf configure --TBB --TBB_ROOT=/usr/include/tbb --BOOST_ROOT=/usr/include/boost,
which ouputed:
Setting top to                           : /home/chensq/tiny-cnn-master 
Setting out to                           : /home/chensq/tiny-cnn-master/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
'configure' finished successfully (0.012s)
Then, I inputed the command: ./waf build, which outputed:
Waf: Entering directory `/home/chensq/tiny-cnn-master/build'
[1/2] Compiling example/main.cpp
../example/main.cpp:31:22: fatal error: tiny_cnn.h: No such file or directory
 #include "tiny_cnn.h"
                      ^
compilation terminated.

Waf: Leaving directory `/home/chensq/tiny-cnn-master/build'
Build failed
 -> task in 'main' failed (exit status 1): 
	{task 139992378742224: cxx main.cpp -> main.cpp.1.o}
['/usr/bin/g++', '-std=c++0x', '-Wall', '-s', '-Ofast', '-I/home/chensq/tiny-cnn-master/build/example', '-I/home/chensq/tiny-cnn-master/example', '-I/home/chensq/tiny-cnn-master/build/include', '-I/home/chensq/tiny-cnn-master/include', '-I/usr/include/boost', '-I/usr/include/tbb', '-DCNN_USE_TBB=""', '../example/main.cpp', '-c', '-o', '/home/chensq/tiny-cnn-master/build/example/main.cpp.1.o']

So I copyed all .h files which are in the tiny_cnn folder into example folder, then I ./waf build again, which ouputed: 
Waf: Entering directory `/home/chensq/tiny-cnn-master/build'
[2/2] Linking build/example/main
/usr/bin/ld: cannot find -lboost_timer-mt
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/chensq/tiny-cnn-master/build'
Build failed
 -> task in 'main' failed (exit status 1): 
	{task 139977480258960: cxxprogram main.cpp.1.o -> main}
['/usr/bin/g++', 'example/main.cpp.1.o', '-o', '/home/chensq/tiny-cnn-master/build/example/main', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L../', '-lstdc++', '-lboost_timer-mt', '-ltbb']
My gcc version is 4.8.2 in the Ubuntu 14.04.
Could you help me? Thank you in advance!

**Comment by ashkanalinejad** [comment]
I have exactly the same problem on my mac ...
also when compiling with clang++ ...

**Comment by shoogle13** [comment]
Instead of moving files, I changed #include "tiny_cnn.h" to #include "../tiny_cnn/tiny_cnn.h" in example/main.cpp, then changed lib= [libcxx, 'boost_timer-mt', 'tbb'] to lib= [libcxx, 'boost_timer', 'tbb'] in wscript and the build was successful. I built boost 1.58.0 without specifying multithreading support, so my files lack the -mt.

**Comment by ChenSiqin** [comment]
@shoogle13 Thanks a lot!

**Comment by varunbezzam** [comment]
I had the same issue as well. Thanks a ton, shoogle13!

**Comment by LiwhoisLi** [comment]
Thank you shoogle 13! But when I solve the 1st problem, there is another one. The new errors are cannot find -lboost_timer-mt and cannot find -ltbb. I don't want to use tbb, so I even didn't include it in the configure phase. Why do they happen?
