### ISSUE TITLE
What is the stop criterion of optimizer

### ISSUE THREAD

**Issue by gadfly10xl** [nyanp/tiny-cnn#36]
What is the stop criterion of these optimization methods?

**Comment by nyanp** [comment]
@gadfly10xl 
One of the easiest ways is to stop training manually when the accuracy on the test (or validation) set stays the same or decreases.
see also:
[http://deeplearning.net/tutorial/gettingstarted.html#early-stopping](http://deeplearning.net/tutorial/gettingstarted.html#early-stopping)
