### ISSUE TITLE
Importing weights

### ISSUE THREAD

**Issue by corby-it** [nyanp/tiny-cnn#39]
Hi,
we are trying to re-implement a cnn  previously trained using keras. We are wondering in which order we should write the weights on a file (a txt file?) in order to be able to import them in a tiny-cnn net.
Unfortunately we couldn't find any documentation about this topic.

**Comment by nyanp** [comment]
@corby-it 
I'm sorry for late reply!
We don't have any documentation about it currently, but I'll write it soon...

**Comment by dicroce** [comment]
I am very interested in this as well as I love Tiny-CNN, and it really is the ideal solution for the kind of embedded ML applications I have in mind, but I am starting to run into its limits with regard to training... If I could train with a GPU (using another lib), and then import the weights that would be amazing....

**Comment by edgarriba** [comment]
@corby-it Still having this issue?

@dicroce It's the midterm schedule add GPU support https://github.com/nyanp/tiny-cnn/issues/187. 
Stay tuned !

**Comment by corby-it** [comment]
@edgarriba Ehm... no. I moved to a different project now! I'm not sure if i'll go back to CNNs soon
