### ISSUE TITLE
Data Normalization

### ISSUE THREAD

**Issue by chenjunlinghao** [nyanp/tiny-cnn#40]
Hello：
    thanks for sharing your code，I use opencv to convert the face images to vect_t, which value is from 0 to 255, I want to know wheather I need to normalize the data from 0 to 1? thanks very much.

**Comment by nyanp** [comment]
@chenjunlinghao 
Here is an example code.
```cpp
    cv::Mat img = cv::imread("test.bmp", 0).reshape(0, 1);
    unsigned char* p = img.ptr<unsigned char>();

    tiny_cnn::vec_t v;

    // transform 0-255(unsigned char) to 0-1(double)
    std::transform(p, p + img.cols, std::back_inserter(v),
                   [&](unsigned char v) { return v / 255.0; });
```
