### ISSUE TITLE
may consume too much memory when creating big network

### ISSUE THREAD

**Issue by shenck0** [nyanp/tiny-cnn#48]
Hi, I'm trying to create a NN like :
``` C++
	nn << convolutional_layer<tan_h>(320, 320, 33, 1, 20)
		<< average_pooling_layer<tan_h>(288, 288, 20, 2)
		<< convolutional_layer<tan_h>(144, 144, 15, 20, 30)
		<< average_pooling_layer<tan_h>(130, 130, 30, 2)
		<< convolutional_layer<tan_h>(65, 65, 6, 30, 20)
		<< max_pooling_layer<tan_h>(60, 60, 20, 3)
		<< fully_connected_layer<tan_h>(8000, 558);
```
but I got "vector subscript out of range" error, it seems like that index3d<T>.size() doesn't return right value when in_ is defined as index3d< unsigned short > type, so I change code:
``` C++
"typedef unsigned short layer_size_t;" => "typedef unsigned int layer_size_t;"
```
but this time, the program is eating memory until whole memory was occupied. (i'm using a 8G RAM)
I think the implement of partial_connected_layer.h is straightforward and intelligible but it may cosume too much memory when creating a big network because of "io/wi/wo_connections".

**Comment by nyanp** [comment]
@shenck0 
Hi, thank you for your report!

As you pointed out, tiny-cnn consume much memory because of io/wi/wo_connections. tiny-cnn is designed for relatively small networks, so speed and memory performance on large networks may be poor. Anyway, tiny-cnn should report more useful information than "vector subscript out of range".

And generally speaking, I think it seems to be very difficult to learn such a huge netoworks without gpu.

**Comment by nyanp** [comment]
@shenck0 
And if you have good idea to reduce memory consumptions, please let me know :)
I want some solution that keep tiny-cnn as intelligible as possible, but I don't have good idea.

**Comment by shenck0** [comment]
Hi, @nyanp 
Now I've realize it's nearly impossible to train such huge CNN like above with CPU only.
And I did some hack which can reduce memory consumption(of io/wi/wo_connections) in some degree, but it's not elegant and efficient:
Consider a io_connections variable (in partial_connected_layer.h). For instance, content is
[(1,0),(2,3),(3,6)], it can be represented by two triplet (1,1,3) and (0,3,3) which means the (a0,d,length) of two arithmetic progression. I use vector<AP_Triplet> like above to replace io/wi/wo_connections variable. And I also change the way about io_connections variable is iterated correspondingly.
Test : Try to create a network like this:
```C++
	nn << convolutional_layer<tan_h>(160, 160, 5, 1, 15)
		<< average_pooling_layer<tan_h>(156, 156, 15, 2)
		<< convolutional_layer<tan_h>(78, 78, 7, 15, 60)
		<< average_pooling_layer<tan_h>(72, 72, 60, 3)
		<< convolutional_layer<tan_h>(24, 24, 3, 60, 80)
		<< max_pooling_layer<tan_h>(22, 22, 80, 2)
		<< convolutional_layer<tan_h>(11, 11, 3, 80, 100)
		<< fully_connected_layer<tan_h>(8100, 559);
```
The program without hack will cost more than 8GB memory which my computer can't afford.
When the AP_Triplet hack is enabled, the program occupied 4.4GB memory when creating NN and 1.7GB memory after creating process.(Using VS2015 Diagnostic Tools)
It can reduce memory consumption but slow down the speed. I run the sample1_convnet() to train a NN(LeNet-5 like) on MNIST data set, and it is about two times slow than the origin implement.
That's the best solution I got for now.

**Comment by shenck0** [comment]
@nyanp 
I created a new branch for demonstrating what I mean in last post.
https://github.com/shenck0/tiny-cnn/tree/patch_reduce_mem

**Comment by nyanp** [comment]
@shenck0 
Thanks! Your hack works very good in large networks, great. As you said, it lacks a bit of clarity and runtime efficiency, but it will help someone who want to train large cnn.

**Comment by nyanp** [comment]
Now implementation of convolutional_layer changed. Memory consumption is independent from sizeof(layer_size_t) and reasonably small :)
