### ISSUE TITLE
tiny-cnn community...

### ISSUE THREAD

**Issue by dicroce** [nyanp/tiny-cnn#55]
First let me say that I love tiny-cnn!

But, I have about a million questions. I think we need a board, or maybe a google group we can post questions to... Also, a wiki for sharing techniques might be nice.

**Comment by nyanp** [comment]
@dicroce 
I'm very happy that you like this library! I've createed mailing list, feel free to join :)
[https://groups.google.com/forum/#!forum/tiny-cnn-users](https://groups.google.com/forum/#!forum/tiny-cnn-users)
I want to update information and guidance for tiny-cnn users (API docs, contribution guides, FAQ, etc), but it take some time to do...

Everyone can edit wiki pages in tiny-cnn. If you have some tips or examples, please share us!
[https://github.com/nyanp/tiny-cnn/wiki](https://github.com/nyanp/tiny-cnn/wiki)
