### ISSUE TITLE
update_weight function

### ISSUE THREAD

**Issue by VPaulV** [nyanp/tiny-cnn#6]
Dear nyanp,

I'm sorry that I created bug report, unfortunately I did not find any other way to communicate with you. (I found your website and page in social network, but there are no email, Skype etc.)
If it is not hard for you, could you explain, please how work update_weight function?
I can not understand how you calculate dW_, Whessian_ and so on.

Sorry for disturb you! 

Best regards,
Paul

**Comment by edgarriba** [comment]
@nyanp Closing this
