### ISSUE TITLE
Is the back_propagation_2nd compute the approximate 2nd derivation?

### ISSUE THREAD

**Issue by dianyancao** [nyanp/tiny-cnn#65]
I am currently add long_short_term_memory lstm_layer to tiny-cnn use for sequence labeling,by modifying the input_layer to recieve the data from fixed size window slide on 2d image.
I find the **back_propagation_2nd** function maybe not compute the 2nd derivation correctlly.
<code>prev_delta2_[c] *= sqr(prev_h.df(prev_out[c]));</code>
Is this compute the approximate 2nd derivation and let it >= 0?

**Comment by bhack** [comment]
Extension to lstm and rnn it is useful. Do you plan to create a PR?

**Comment by bhack** [comment]
@dianyancao Do you plan also to add a graph computation API?

**Comment by dianyancao** [comment]
@bhack ,I am sorry for late reply,I leave it down,now is moving to caffe.

**Comment by edgarriba** [comment]
@dianyancao 

Notice that a new version of tiny-cnn has been released with a lots of new features. Are still interested in implement RNN/LSTM ?

https://github.com/nyanp/tiny-cnn/releases/tag/v0.1.0

**Comment by dianyancao** [comment]
@edgarriba 
Yes,thanks for all! Now tiny-cnn takes into a new aspect.I will try it later.
