### ISSUE TITLE
CMakeLists.txt out of sync

### ISSUE THREAD

**Issue by binary42** [nyanp/tiny-cnn#69]
Looks like you need to update the CMakeLists.txt to accomadate the re-factored library directory structure. i.e. tiny_cnn/convolutional_layer.h to tiny_cnn/io/convolutional_layer.h , etc.

**Comment by nyanp** [comment]
@binary42 
Thanks for your information! I hope @mrazekv will fix it on #67 :)

**Comment by mrazekv** [comment]
@binary42 
I have already fixed it. The new version is in the pull request #67 ;-)

**Comment by nyanp** [comment]
@mrazekv 
I've merged it. Thank you very much!
