### ISSUE TITLE
Crash in dropout_layer.

### ISSUE THREAD

**Issue by dicroce** [nyanp/tiny-cnn#70]
If you use the &lt;&lt; operator of network to construct your network the raw mask_ pointer member in dropout_layer causes a crash because the default copy ctor and assignment op don't deep copy mask_ (and a copy occurs in <<).

I have local changes that convert mask_ into a vector of uint_8 and it fixes the issue because std::vector implements copy construction and assignment operators and the default implementation that do memberwise =  then work for dropout_layer.

Unfortunately, we cannot just use vector&lt;bool&gt; because vector&lt;bool&gt; is a specialization that works differently than vectors normally work and operator [] is not an l-value...

So, I can check in my changes... OR if you prefer I could implement assignment operators and copy constructors for dropout_layer... that would also work.

**Comment by dicroce** [comment]
I changed my implementation to one that implements assignment and copy ctor... While this means adding 2 new functions to dropout_layer.h, it requires the least amount of changes to the forward_propagation() and back_propagation() methods.

**Comment by nyanp** [comment]
@dicroce 
Thanks for your information :) Implementing assignment and copy ctor will be nice, could you make a pull request for this problem?
