### ISSUE TITLE
Replace TBB with simpler thread pool

### ISSUE THREAD

**Issue by nyanp** [nyanp/tiny-cnn#72]
tiny-cnn requires intel TBB to multi-threading, but tiny-cnn use only tbb::parallel_for. To maximize portability, replace TBB with simpler (header only and dependency-free) C++11 implementation would be nice.

**Comment by patrikhuber** [comment]
I can recommend this: https://github.com/progschj/ThreadPool
I've used it in my cross-platform projects and I'm very happy with it. It also seems very well tested, it's active on GitHub, a few people contributed and issues were solved.
(I am not associated with it at all, just recommending.)

**Comment by nyanp** [comment]
@patrikhuber 
It looks very nice :) Simple, portable and header-only are good features for tiny-cnn. I'll try to use it, thanks!

**Comment by DozerTheCat** [comment]
Threading is also supported through OMP, which I found to be less buggy than nyanp's TBB implementiation.

**Comment by edgarriba** [comment]
@nyanp Currently OMP is supported. Is this solved in version v.0.1.0 ?

**Comment by nyanp** [comment]
OpenMP is supported and pure C++ implementation is used by default from 0b25853 . This issue solved
