### ISSUE TITLE
'tiny_cnn::for_' :  ambiguous call to overloaded function

### ISSUE THREAD

**Issue by stereomatchingkiss** [nyanp/tiny-cnn#79]
Compiler : vc2013 64bits
OS : win8 64bits

When I try to run the mnist example(with some change), I got this [error message](http://pastebin.com/73wYAnyC). 

    network<mse, adagrad> nn; // specify loss-function and learning strategy

    using activate = relu;
    nn << convolutional_layer<activate>(32, 32, 5, 1, 6, padding::same)
         << average_pooling_layer<activate>(32, 32, 6, 2)
         << convolutional_layer<activate>(16, 16, 5, 6, 16, padding::same)
         << max_pooling_layer<activate>(16, 16, 16, 2)
         << convolutional_layer<activate>(8, 8, 5, 16, 8)
         << fully_connected_layer<activate>(128, 10);

A quick fix is remove one of the function, a longer fix is change the type of end to template, use type_traits to do compile time checking

    template<typename T, typename Func>
    inline
    void for_(std::true_type, bool parallelize, int begin, T end, Func f, int grainsize = 100){
        parallelize = parallelize && value_representation<int>(end);
        parallelize ? parallel_for(begin, static_cast<int>(end), f, grainsize) : 
        xparallel_for(begin, static_cast<int>(end), f);
    }

    template<typename T, typename Func>
    inline
    void for_(std::false_type, bool parallelize, int begin, T end, Func f, int grainsize = 100){
       parallelize ? parallel_for(begin, static_cast<int>(end), f, grainsize) : xparallel_for(begin, end, f);
    }

    template<typename T, typename Func>
    inline
    void for_(bool parallelize, int begin, T end, Func f, int grainsize = 100) {
        static_assert(std::is_integral<T>::value, "end must be integral type");
        for_(typename std::is_unsigned<T>::type(), parallelize, begin, end, f, grainsize);
    }

Edit : I am not sure this is a correct solution, if you think it is ok, I would open a PR

**Comment by Abai** [comment]
See #78 and #77 This should be fixed after #77 was merged in yesterdam.
