### ISSUE TITLE
Some thoughts on casts and _t(ypes)

### ISSUE THREAD

**Issue by pansk** [nyanp/tiny-cnn#88]
I notice we're fixing quite a lot of casts in the last days. I think this could suggest some other possible type refactorings.

Take this as an example: label_t is an index in the output layer, and the size of a layer is defined as layer_size_t. Shouldn't label_t be layer_size_t? (it isn't right now).

The reason why layer_size_t isn't size_t was to reduce memory footprint of connection matrices in the partially_connected_layer (which was used by convolutional layer - but this is no longer happening). Is this still valid? If not, we can just give up the layer_size_t and label_t altogether (or just define them to be size_t)

Should the *_t s be part of a configuration? Their definition is in util.h right now. 

Moreover, I'd like to compare results from float and double networks (I obtained quite different results with two successive trainings), so it could be interesting to have some kind of template parameter for float_t, and not a global definition in util.h.

**Comment by nyanp** [comment]
+1

> The reason why layer_size_t isn't size_t was to reduce memory footprint of connection matrices in the partially_connected_layer (which was used by convolutional layer - but this is no longer happening). Is this still valid? If not, we can just give up the layer_size_t and label_t altogether (or just define them to be size_t)

No longer valid. In the old implementation, memory consumption in convolutional layer scale linearly with ```sizeof(layer_size_t)```, so we had to keep size of ```layer_size_t``` small (#48) - but now convolutional layer doesn't consume such memory (pooling layer still depends on ```sizeof(layer_size_t)```, but it's not critical in most case). So now we can merge ```layer_size_t``` and ```label_t``` as some appropriate name (```cnn_size_t```, for example. do you have any idea?).

I think moving *_t into config.h is good idea.

> Moreover, I'd like to compare results from float and double networks (I obtained quite different results with two successive trainings), so it could be interesting to have some kind of template parameter for float_t, and not a global definition in util.h.

It's very convenient if we can compare and import/export results between various arithmetic type networks (float, double, half-float, fixed point...). It requires a lot of changes in tiny-cnn codebase, so it's an different issue from type-cast warnings. I'll make another issue about this.

**Comment by pansk** [comment]
If sizeof(layer_size_t) is not a problem anymore, I'd go for vec_t::size_type (which should be size_t, in most implementations). We can define a cnn_size_t to that, and it would reduce conspicuously the number of casts required in the code.

**Comment by edgarriba** [comment]
@nyanp @pansk Fixed in last version
