### ISSUE TITLE
compile failed by missing caffe.pb.h. Please help how to find this files. Thanks

### ISSUE THREAD

**Issue by Thanh-Binh** [nyanp/tiny-cnn#89]

**Comment by Abai** [comment]
If you are trying to use caffe converter, then you need to run protobuf to generate caffe.pb.h and caffe.pb.cc. Read here for the instructions:

https://github.com/nyanp/tiny-cnn/blob/master/examples/caffe_converter/readme.md

**Comment by Thanh-Binh** [comment]
thanks. I did it.
But have the new error of caffe.pb.h like:
1>e:\Projects\DeepLearning\tiny-cnn-master\tiny_cnn/io/caffe/caffe.pb.h(2606): error C2059: Syntaxfehler: 'Konstante'
1>e:\Projects\DeepLearning\tiny-cnn-master\tiny_cnn/io/caffe/caffe.pb.h(2606): error C2238: Unerwartete(s) Token vor ';'
1>e:\Projects\DeepLearning\tiny-cnn-master\tiny_cnn/io/caffe/caffe.pb.h(8758): error C2059: Syntaxfehler: 'Konstante'
1>e:\Projects\DeepLearning\tiny-cnn-master\tiny_cnn/io/caffe/caffe.pb.h(8758): error C2238: Unerwartete(s) Token vor ';'

Do you have any idea for solving it? Thanks.

**Comment by Abai** [comment]
I'm sorry, I mostly use linux and osx to build stuff and from your error on windows it is not clear what is the problem.

**Comment by pansk** [comment]
I can't read German yet.
Which compiler/version are you using?

**Comment by Thanh-Binh** [comment]
Thanks. In meantime it is solved.

**Comment by Thanh-Binh** [comment]
To Abai: Do you have a runable caffe-model etc. for testing with tinycnn? I mean:
 deploy.prototxt\
 bvlc_reference_caffenet.caffemodel\
 imagenet_mean.binaryproto\
 synset_words.txt\
 cat.jpg

Thanks

**Comment by Abai** [comment]
You can get all the necessary files from caffe repository.

**Comment by jamseams** [comment]
@Thanh-Binh : Were you successful in running the caffe_converter?

**Comment by edgarriba** [comment]
@Thanh-Binh  Notice that in the next release tiny-cnn will autogenerate caffe proto headers
https://github.com/nyanp/tiny-cnn/blob/feat/generic-computational-graph/CMakeLists.txt#L231

@nyanp issue solved
