### ISSUE TITLE
Having some problems in Ubuntu 14.04

### ISSUE THREAD

**Issue by neil50111** [nyanp/tiny-cnn#95]
Hello, i've tried this on Ubuntu 14.04, and now i've met some problems.
i've install tbb via "sudo apt-get install libtbb-dev", and i follow the steps in README, as i type the first command : ./waf configure ... , it showed as follow
Setting top to                           : /home/f5009b/tiny-cnn-master 
Setting out to                           : /home/f5009b/tiny-cnn-master/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
enable option:TBB(root=/usr/include/tbb)
'configure' finished successfully (0.510s) 

i'm no sure if it contain any error, but when i type the next command : ./waf build, it show as follow
Waf: Entering directory `/home/f5009b/tiny-cnn-master/build'
No wscript file in directory /home/f5009b/tiny-cnn-master/example

i've checked the example directory and that already contained the wscript file. 
i've no idea where the problem is, please answer me for that, thanks.

**Comment by nyanp** [comment]
@neil50111 
Sorry, waf build is out of date. I'll fix it.
Please try later, or you can use CMake instead :)

**Comment by neil50111** [comment]
Oh, thx for fixing that :)
i'll try it later !

**Comment by neil50111** [comment]
Oh, it worked as follow
Waf: Entering directory `/home/f5009b/tiny-cnn-master-fix/build'
[1/2] Compiling examples/main.cpp
[2/2] Linking build/examples/main
Waf: Leaving directory `/home/f5009b/tiny-cnn-master-fix/build'
'build' finished successfully (10.078s)

i think it finished successfully.
After that i check the "build" folder, in the example, there is an executable file named main.
i have no idea how to run it, or i need to get other tool to do it ?

**Comment by nyanp** [comment]
@neil50111 
Yes, you finished build successfully.
Just execute this file and sample training ([mnist](http://yann.lecun.com/exdb/mnist/) digit classification) will start. If you are familiar with c++, read examples/main.cpp for detail.

**Comment by neil50111** [comment]
Oh, thx very much 
i've successfully run on Ubuntu 14.04 & VC2013
and get 98.85 & 98.94 of accuracy individually
thanks again

**Comment by nyanp** [comment]
@neil50111
I'm glad to hear that, have a nice day ;)
