### ISSUE TITLE
Should we scale the activation value of dropout when predict?

### ISSUE THREAD

**Issue by stereomatchingkiss** [nyanp/tiny-cnn#96]
According to the [video ](https://www.youtube.com/watch?v=hd_KFJ5ktUc&feature=youtu.be)of [cs231n](http://cs231n.stanford.edu/syllabus.html) at 51:30, the activation of the dropout should be rescaled, so the output at text time == expected output at training time. 

Should we scale it?from

```
for (size_t i = 0; i < in.size(); i++)
      a[i] = out[i] = in[i];
```

To

```
if(rescale){
  for (size_t i = 0; i < in.size(); i++)
      a[i] = out[i] = in[i] * scale_;
}else{
    for (size_t i = 0; i < in.size(); i++)
      a[i] = out[i] = in[i];
}
```

Besides, when we want to predict(test) the results with dropout layer, do we need to initialize the net_phase explicit?

Ex : When training(pseudo codes)

```
 dropout_layer(16*16*32, 0.25)
```

When predict

```
dropout_layer(16*16*32, 0.25, net_phase::test)
```

I check the source codes of predict, but I cannot find it set the net_phase from train to test, do we need to set it from train to test manually?Thanks

**Comment by stereomatchingkiss** [comment]
If tiny-cnn did not turn the phase from training to test phase when testing and vice versa, should we add them in the api? 

Should we provide an api to change the phase of the whole network from train to test and vice versa?

Thanks

**Comment by pansk** [comment]
+1 for providing the train/test switch to the api

**Comment by miradel51** [comment]
+1





|
MiradelPHD candidate
miradel51@126.com
Lab：Tsinghua NLP & CSS Lab
Room 4-506,FIT building,Tsinghua University,Beijing,China
Computer Science & Technology
Mobile：13051308938
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|

在 2016-02-20 22:26:16，"Marco Foco" <notifications@github.com> 写道：


+1 for providing the train/test switch to the api

**Comment by stereomatchingkiss** [comment]
What about scaling?Not a good idea?

**Comment by pansk** [comment]
I didn't comment on scaling because I lack the knowledge to take a position on that.

**Comment by nyanp** [comment]
Yes, we should scale the activation value to be matched between training and testing phase.
tiny-cnn scale the activation in training phase instead of testing (it is equivalent), so it is as it should be :)

Providing api for context-switching is needed, and @stereomatchingkiss do this work in #98 (thanks!). I'll merge it later.
